### ISSUE TITLE
Bitcoin references need to be updated

### ISSUE THREAD

**Issue by benma** [litecoin-project/insight-ui#2]
Hi

I noticed that the status page (https://insight.litecore.io/status) still says "Bitcoin node information" instead of "Litecoin node information". Grepping the repo uncovers many more bitcoin references.

**Comment by losh11** [comment]
Yes, working on this alongside other UI changes.

**Comment by thrasher-** [comment]
PR submitted: https://github.com/litecoin-project/insight-lite-ui/pull/4
